QTERMWIDGET_VERSION = 0.14.1
# QTERMWIDGET_SITE = $(call github,lxqt,qtermwidget,$(QTERMWIDGET_VERSION))
QTERMWIDGET_SOURCE=qtermwidget-$(QTERMWIDGET_VERSION).tar.xz
QTERMWIDGET_SITE = https://downloads.lxqt.org/downloads/qtermwidget/$(QTERMWIDGET_VERSION)

QTERMWIDGET_INSTALL_STAGING = YES
QTERMWIDGET_INSTALL_TARGET = YES
QTERMWIDGET_DEPENDENCIES = qt5base

$(eval $(cmake-package))
